baseurl = "https://geoffholden.com/"
languageCode = "en-us"
title = "Geoff Holden"

# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
theme = "hugo-profile"

ignoreErrors = ["error-missing-instagram-accesstoken"]

[params.color]
    primaryColor = "#005700"

[params.color.darkmode]
    primaryColor = "#00a900"

[permalinks]
    post = "/:year/:month/:filename/"

[blackfriday]
    extensions = ["definitionLists","headerIds"]
    extensionsmask = ["autoHeaderIds"]
    plainIdAnchors = true

[params]
    site_author = "Geoff Holden"
    site_description = "The personall blog of Geoff Holden"
    location = "Newfoundland, Canada"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "img/profile.jpg"
    header_background = "img/desk.jpg"
    header_title = "Ponderings of a Programmer"
    copyright = "Geoff Holden"

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-230660-1"

    disclaimer = "This is my personal blog any views expressed here are mine alone and not those of my employer or anybody else you might pin them on."

    favicon = "/img/monogram.svg"

    [params.hero]
        enable = true
        intro = "Hi, my name is"
        title = "Geoff Holden."
        subtitle = "I make things."
        image = "/img/pixel.png"
        [params.hero.button]
            enable = true
            name = "Resume"
            url = "/resume/"

    [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-github"
        url = "https://github.com/geoffholden/"

    [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/geoffholden"

    [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fas fa-camera"
        url = "https://gkhphoto.com/"

    [[params.hero.socialLinks.fontAwesomeIcons]]
        icon = "fas fa-camera-retro"
        url = "https://film.gkhphoto.com/"

    # [[params.hero.socialLinks.fontAwesomeIcons]]
    #     icon = "fas fa-blog"
    #     url = "https://GettingThingsStarted.com/"

    [params.about]
        enable = true
        title = "About Me"
        image = "/img/hero.jpg"
        content = """I am a software developer and electronics designer based out of St. John's, NL, Canada.

I'm currently working with Seaformatics, where I design the electronics for the [WaterLily](https://waterlilyturbine.com/) personal turbine.

        """

        [params.about.skills]
            enable = true
            title = "Here are a few technologies that I'm proficient with:"
            items = [ "C/C++", "Java/Kotlin", "Flutter", "React", "Python", "Go", "Ruby", "Eagle", "KiCAD" ]

    [params.contact]
        enable = true
        content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
        email = "geoff@geoffholden.com"
        btnName = "Mail me"

    [params.footer]
        recentPosts = false

        [params.footer.socialNetworks]
            github = "https://github.com/geoffholden/"
            linkedin = "https://linkedin.com/in/geoffholden"
