baseurl = "http://geoffholden.com/"
languageCode = "en-us"
title = "Geoff Holden"

[blackfriday]
  extensions = ["definitionLists","headerIds"]
  extensionsmask = ["autoHeaderIds"]
  plainIdAnchors = true


